
spring:
  datasource:
    url: jdbc:mysql://192.168.160.224:3306/mall?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


mbgp:
  packageConfig:
    parent: com.wisdom.plugin.demo.mbgp
